src/components/Nav.js

After aligning on the content strategy for MVP, I wanted to switch "recovery resources" back to "Getting started." Also, this is my first commit on federalist so going to create a pull request in case I'm doing it incorrectly! :)

Changing back to 'Getting started'

---

src/actions/facilities.js
src/utils/api.js
src/utils/filters.js

Fixes https://github.com/18F/samhsa-prototype/issues/14
Fixes https://github.com/18F/samhsa-prototype/issues/17
Refactors the way the params are prepared to be sent to the endpoint, no longer relying on URLSearchParams which is not cross browser compatible.
Also adds additional options to the `Type of Care` filter.

Remove URLSearchParams

---

src/components/Form/Filters.js
src/components/Input/Label.js
src/plugins/filters.js
src/utils/api.js
src/utils/filters.js

Fixes https://github.com/18F/samhsa-prototype/issues/16
Using the `format` and `normalize` functions of redux-form in order to store the `sCodes` value of the checkboxes rather than a boolean value.
Preview: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/samhsa-prototype/bh-adv-filters/

Add additional advanced filters

---

src/utils/api.js

The `All` value for distance was falling through the reducer and getting added to `sCodes`, this makes sure it is handled properly.

Handle 100+ distance properly in new api reducer

---

package-lock.json
package.json
src/components/App.js
src/components/Home.js
src/components/Page.js
src/utils/misc.js
src/utils/topics.js

Adds a new view for content based pages. As it stands now, the content is pulled out into `utils/topics.js` - and if the `body` of a `subTopic` is empty its just filled with lorem ipsum. The way all of this works will need to be refined so that we can support things like inline formatting and links within the content, but this helps gets some of the pieces in place.
I also linked up the homepage cards to the corresponding pages for the time being.
Preview: https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/bh-content-page/

Add content page template

---

src/components/Form/Filters.js
src/components/Form/Homepage.js
src/components/Home.js

- Removed reference to state in search box placeholder text (assuming these are the only references?)
- Made substance use and addiction bold in 'Find help' subtitle (Nick's suggestion for now, based on our ask about how to make that more prominent)

Updates based on team audit session

---

src/components/Map/InfoWindowText.js

This was left out of https://github.com/18F/samhsa-prototype/pull/71 and is required for the links on the map popups to properly route to the detail page.

Fix for map link

---

src/actions/facilities.js
src/actions/filters.js
src/components/Form/Filters.js
src/components/Form/Homepage.js
src/plugins/filters.js
src/reducers/facilities.js

Fixes https://github.com/18F/samhsa-prototype/issues/89
Alternate approach for location bug fixed in https://github.com/18F/samhsa-prototype/pull/94. Also ensures that facilities store is cleared when filter form is reinitialized so results and filters do not become out of sync.

Use enableReinitialize option on filters form

---

src/plugins/filters.js
src/utils/constants.js
src/utils/topics.js

This is required in order to clear the value upon hiding the advanced filters. Also moved the advanced filter array and default distance to constants file so they are more visible.

Capture age in filters reducer

---

src/components/Card.js
src/components/Home.js
src/components/Nav.js
src/components/Page.js
src/utils/topics.js

- Added 'what to expect' content from Amanda 
- Updated home page ledes
- Added subtitle under "what to expect" on homepage (I asked Nick to provide more feedback on this as part of his work on that section)
Still to do, which might be better for @hursey013 to do: 
- Link to the 'what to expect' content section in top nav
- Remove subtopic from 'what to expect' section (Note: @hursey013 - Can we make it so that we don't have subtopics for this section? Ideally there are no jump downs within this section, but we could always get Amanda to write something else. For now, I have "what to expect" again as a placeholder.)

Updated 'What to expect' and other content changes

---

public/index.html
src/middleware/analytics.js
src/store.js

For #60, this allows snapshot tracking for:
Landing page
Details page
Results List page
Each individual content page
Needs setup on CE as well,

Setting CrazyEgg snapshot tracking names for a handful of components

---

src/actions/facilities.js
src/components/Details.js
src/middleware/analytics.js
src/reducers/facilities.js

Fixes https://github.com/18F/samhsa-prototype/issues/62
This adds some visual feedback for when a facility is reported:
...and limits reporting to once per session. The caveat being since it's not currently stored anywhere, reloading the app would allow someone to report the facility again. Future PR could make use of localStorage to make remembering what facilities have been reported more sticky.
This needs some tests, but will follow up with them in a future PR as well.

Add reported facility to store

---

src/components/Pagination.js
src/components/ResultsList.js
src/utils/api.js
src/utils/constants.js

Right now on the results page it shows something like `Showing page 2 of 2 (14 results)` which is not a common way to describe the current result set.
This updates the page to display the current range instead, such as `Showing 1-10 of 19`.

Display current number range of results

---

src/components/App.js
src/components/Card.js
src/components/Details.js
src/components/Footer.js
src/components/Header/index.js
src/components/Results.js
src/components/ResultsList.js
src/css/tailwind.src.css
src/tailwind.js

Fixes https://github.com/18F/samhsa-prototype/issues/31
Optimized the results list and facility page for printing. Upon printing the following areas will be hidden:
- Header/navigation
- Filter box
- Footer
I also selectively hid some buttons and links that were not relevant for a printing and changed colored text/links to black. There are likely some more optimizations to make, but this addresses the basics and can be adapted once a more final design is in place.

Add print styles

---

src/components/Header/HeaderNav.js
src/components/Header/HeaderNav.test.js

Fixes https://github.com/18F/samhsa-prototype/issues/153
This will listen for route changes and force close the mobile nav anytime there is a change.

Collapse mobile menu when route changes

---

src/components/Error.js
src/components/Results.js
src/reducers/facilities.js

Fixes https://github.com/18F/samhsa-prototype/issues/43
Adds error page in case vendor endpoint is down. Including screenshot of page since there is no easy way to reproduce on preview site:

Add error page for when endpoint is down

---

src/components/Map/MapContainer.js
src/components/Map/MapContainer.test.js
src/setupTests.js

For #186, we add a `title` to each iframe when rendered and ready for interaction on the page.

Add title attributes when rendering google maps iframes

---

src/components/Card.js
src/components/Details.js
src/components/Input/Button.js
src/components/Pagination.js
src/components/ResultsList.js

Herein, for #187, we darken the grey used as `text-color` and blue used as button backgrounds to reach a desired contrast ratio of 4.5:1 throughout the site.

Improve contrast by darkening text and backgrounds

---

src/components/Card.js
src/components/Input/Button.js
src/components/Map/InfoWindowText.js

For #189, we render the links to facility details from the Results page as a single anchor element. 
This includes a small visual change as we're falling back on the existing styling for ` <Button 
as={Link} outline="true" ...`

Single focusable element for facility details links

---

src/components/Form/FormFilters.js

When initiating a search from the homepage, a facility search is kicked off, but for one reason or another the search is kicked off a second time when the filter form is loaded on the results page (presumably because initializing the location field with the homepage value is triggering a change).
I attempted to use the `dirty` prop to prevent this from happening, but it was having some unintended consequences. `dirty` checks to see if any of the values are different from the initialized values, which works, until you return a value to it's initial value (like setting distance to 50mi, then back to the original 25mi) which will not load in new results.
Removing the `dirty` prop for now will make filtering more predictable, however I will circle back in another PR to figure out why the …

Temporary fix for automatic filtering

---

src/actions/facility.js
src/components/App.js
src/components/Card.js
src/components/Details.js
src/components/Details.test.js
src/components/Map/InfoWindowText.js
src/reducers/facility.js
src/reducers/index.js
src/utils/constants.js
src/utils/misc.js

Fixes https://github.com/18F/samhsa-prototype/issues/146
Piggybacking off of @keithnorm's workaround here: https://github.com/18F/samhsa-prototype/pull/180 this adds the ability to navigate directly to a facility page, enabling folks to share/bookmark specific facilities.
By using a path of `/details/:frid/` along with the lat and long appended as query parameters, we are able to use the existing endpoint to search by lat/long (limiting results to only facilities with the exact lat/long), and then further filter by FRID in order to narrow the results to a single facility. This is accomplished with a single call to the endpoint.
In the future, if a new FRID specific endpoint is enabled, the `/details/:frid/` path can continued to be used (preserving existing links), and the additional …

Route to facility page based on FRID

---

src/components/Header/HeaderBeta.js
src/components/Home.js
src/utils/api.js
src/utils/api.test.js
src/utils/constants.js
src/utils/content.js
src/utils/filters.js

Updates based on #214 
- Changed subtitle on home page to "Quickly find providers who treat substance use disorders and addiction" (remove mental illness)
- Removed 'mental health services only' and 'psychiatric emergency walk-in' from info content Treatment Options > Types of treatment
- Added SU-specific wording to beta banner
- Removed 'mental health services only' and 'psychiatric emergency walk-in' filters
NOTE: @hursey013 -We still need to:
- Change the co-occuring filter so that it returns SA only
- Make any other endpoint logic changes necessary (ensuring only SA facilities are returned globally)

Remove MH results from prototype

---

src/components/Form/FormFilters.js
src/components/Input/Location.js

Sending an empty location causes a server error on the production endpoint. This can be seen in the steps outlined in https://github.com/18F/samhsa-prototype/issues/226. This prevents the filters form from submitting without a valid location.
I think there are definitely some bigger UX issues/questions associated with default/empty location behavior though that will need to be explored/tested more thoroughly.

Prevent empty location value in filter input

---

src/components/Form/FormFilters.js
src/components/Form/FormHomepage.js
src/plugins/filters.js
src/plugins/filters.test.js

Currently, when navigating directly to `/results` the distance dropdown is unset and shows `100+ miles`. This updates the logic to use the defined default distance.

Respect default distance when navigating directly to /results

---

src/components/Input/Location.js

Allow location input to be submitted by pressing enter.
Addresses feedback:
> Weird thing where typing a zip and hitting enter won’t search - I have to either tab over or click the search button

Submit location on pressing enter

---

src/components/Form/FormFilters.js
src/components/Form/FormFilters.test.js

Right now the languages endpoint is hit every time the filters component is mounted (which happens frequently when navigating back and forth between facility detail pages and results). This limits the request to just one time per session since it's only necessary to grab the information once.

Only fetch languages once

---

src/components/Form/FormFilters.js

When the results page is loaded, it should look for filter values in the following order:
- If there are existing values already set in the filters form
- If not, check if there are values being sent from the homepage
- If no values are set at all, use the `initialValues` object to initialize the form
Previously, the first two bullet points were switched, causing stale homepage values to override values set in the filters themselves.
To replicate:
> when I filter by 'type of treatment' & change distance, and then view provider details on any facility card, and then click on 'back to search results' - the distance resets to 25 and the type of treatment changes to the blank default, but I think it is still keeping my original search query. Is there any way to keep the search criteria people …

Check for filter values in proper order

---

src/actions/filters.js
src/actions/filters.test.js
src/actions/ui.js
src/actions/ui.test.js
src/components/Form/FormFilters.js
src/components/Form/FormFilters.test.js
src/plugins/filters.js
src/plugins/filters.test.js
src/reducers/index.js
src/reducers/ui.js
src/reducers/ui.test.js
src/utils/constants.js

Fixes https://github.com/18F/samhsa-prototype/issues/265
Fixes https://github.com/18F/samhsa-prototype/issues/264
Moves the opened/closed state of the "more filters" section to the redux store in order to retain the current state while navigating to and from the results. Also removes logic which clears the values in "more filters" when section is collapsed.

Improve filter interaction based on feedback

---

src/utils/filters.js

We decided to remove the "all types of treatment" default option from the MAT filter section. It was confusing to people in usability tests. 
Resolves #293

Remove 'all types of treatment' option from MAT section

---

src/components/Input/Label.js
src/components/Input/Radio.js

Resolves #330 
I believe this addresses everything but changing the color of the radio inputs. Per my comment on the issue, I am guessing that implementing custom inputs JUST to change the color is probably out of scope for the MVP...
Changing the size of the radio inputs on mobile is done with `transform: scale(1.25)`. This appears OK when viewing the "mobile" site in Mac Chrome, but needs some browser testing, especially on mobile, to make sure this is working as intended.

Filter enhancements

---

src/components/Input/Button.js

Resolves #307 
Adds the `disabled` attribute to `Button`s when they are disabled.
@iamjolly I don't think this is your preferred approach, but this is MUCH quicker right now than showing the error message on submit of no data. If we still want to enhance this to use other behavior, perhaps we can roll it into #308 and reprioritize.

Add disabled attr to button when disabled

---

src/components/Details/DetailsLocation.js
src/components/Details/DetailsLocation.test.js

Removes the `Ask them about it when you call.` sentence when a facility does not offer transportation assistance.

Modify conditional content for transportation callout.

---

src/components/Warning.js

Add info-circle icon to warning box:

Add info icon to before you call warning box

---

src/components/Form/FormFilters.js
src/components/Form/FormFilters.test.js

Smooths the transition when populating the button with the number of results on mobile.
**Preview:**

Add small animation to mobile button when results are being retrieved

---

src/components/Home.js

Fixes https://github.com/18F/samhsa-prototype/issues/313
Resolves an issue with how the images were rendering on the homepage in Edge.
Screenshot after fix:

Fix homepage image width on IE Edge

---

src/components/Input/Label.js
src/components/Input/Location.js

Fixes https://github.com/18F/samhsa-prototype/issues/315
Block level elements are not allowed in `<label />` so this removes them. Also, the second part of  https://github.com/18F/samhsa-prototype/issues/315, `value attribute not allowed on label element` has since been fixed in another PR.

Remove block level elements from label

---

src/components/Form/FormFilters.js
src/components/Form/FormFilters.test.js
src/components/Results/index.js

Resolves #397 
This is not my ideal solution, but it seems to work. Ideally, when the form submits successfully, the form is reset to a "pristine" state such that we can just check the `touched` or `dirty` values to determine if any values changed and omit submitting if so. Unfortunately, there are some issues with how we are using `redux-form` that is preventing this solution but are out of the scope of this issue.
If it is worth the time, someone can go through in detail and create some issues on the backlog to refactor some of this.

Prevent duplicate searches

---

src/components/Details/DetailsPayment.js
src/components/Details/DetailsPayment.test.js

Resolves https://github.com/18F/samhsa-prototype/issues/364
Shows message on details page when no payment options are available:

Show message when no payment options are available

---

src/components/Results/index.js
src/components/Results/index.test.js

Resolves https://github.com/18F/samhsa-prototype/issues/325
To test, on mobile, without setting a location go to `Search for treatment` in the mobile menu and observe that the filters are expanded. Go back to homepage, search for a location from the homepage as you typically would, observe that when the results are loaded the filters are collapsed.

Expand filters by default if no location is set

---

src/components/Card.js

Fixes https://github.com/18F/samhsa-prototype/issues/340
**Before:**
**After:**

Make card focus outline visible

---

src/components/Input/Location.js

Add a small amount of additional padding so text does not flow into icon.
Before:
After:

Add extra padding to location search box

---

src/components/App.js
src/components/Input/Location.js

Resolves https://github.com/18F/samhsa-prototype/issues/243
For all Google Places API errors: capture the status code in Google Analytics, and redirect to the `/error` page for all status codes that are not `OK` or `ZERO_RESULTS`.
Not sure how to best test that this is working as intended given the mix of dependencies (redux-form and react-places-autocomplete).

Capture Google Places API errors

---

.env.production
src/components/App.js
src/components/Home.js

Federalist does not expose an env var that contains the root domain name and a few of our meta tags rely on having a full absolute url vs a relative path. I've configured a new env var to refer to our prod domain name so that we can make sure the URLs are formed correctly, however for the time being I'm using `findtreatmentbeta.18f.gov`. When it comes time to launch on findtreatment.gov, this will need to be updated.

Use absolute URL for meta tags

---

src/components/Footer.js

When we go live on FindTreatment.gov, we'll want to remove the link to the existing locator from the beta banner, so I've included it in the "Other resources" section in the footer. I've added a note in #344 to remove it from the banner before we go live.

Add link to findtreatment.samhsa.gov in footer

---

.env.development
.env.production
src/actions/facilities.js
src/actions/facility.js
src/utils/api.js

Retargeting the `production` instance to the new API endpoint
As the beta/production endpoint names have diverged, herein we also move the final absolute endpoint into configuration and do not pass any additional paths to axios.

New production endpoint

---

src/actions/facility.js

Resolves #469 
When filtering by distance, the API endpoint excludes results with distances equal to the provided
limit. 
e.g. 0 meters from the queried point.
To include those results, and allow the FRID specific filtering to function, we bump our limits by 1 meter herein.

Increase facility filter request to 1m

---

src/components/App.js

Resolves #488 
If the path (url) doesn't change, do NOT rerender the `App` component. This means that no analytics events will fire and the title and focus won't change.
I think this is the intended behavior and everything looks ok to me, but please play around and make sure this doesn't have unintended consequences.

Do not rerender component if path does not change

---

src/components/Home.js

For better keyboard accessibility, this moves the focus to the `What to expect` section when the `Learn more` button is clicked on the homepage.

Move focus to What to Expect section when Learn more is clicked

---

src/components/Card.js
src/components/Details/DetailsLocation.js
src/components/Details/index.js
src/components/Error.js
src/components/Footer.js
src/components/Header/HeaderBeta.js
src/components/Header/HeaderHelpLine.js
src/components/Map/MapStatic.js
src/components/OutboundLink.js
src/components/OutboundLink.test.js
src/components/Results/NoLocation.js
src/components/Results/NoResults.js

Resolves #494 
This provides a one stop shop for controlling whether our external (or outbound) links open in a new tab. The current default is set to `true`. Email (`email:`) and telephone (`tel:`) links are excluded and will not receive the attributes to open in a new tab.
This just wraps the existing `OutboundLink` component provided by Google Analytics so that functionality should remain unchanged.
Also adds `rel="nooponer noreferrer"` attribute to the link.

Universally control whether external links open in a new tab, defaults to TRUE

---

src/components/Results/index.js

Using `display: initial` when conditionally rendering the results and the filters does not work! Use `display: block;` instead!
https://caniuse.com/#search=initial

use display: block; HOTFIX!

---

src/components/Results/index.js

Resolves #415 
Inspired by https://github.com/18F/samhsa-prototype/pull/522/files, but wanted to keep the scroll behavior consistent between desktop and mobile.

Scroll to top header on mobile after filters are closed

---

src/components/App.js

It appears that the https://www.findtreatment.gov site was crawled but not indexed due to the following error.
Per https://support.google.com/webmasters/answer/7440203#duplicate_page_without_canonical_tag
https://support.google.com/webmasters/answer/139066
Add the "canonical url" to each page.

Add canonical url

---

src/components/Details/index.js

Fixes https://github.com/18F/samhsa-prototype/issues/519
Uses tailwind's `truncate` CSS class https://tailwindcss.com/docs/word-break/#truncate

Truncate long urls on details page

---

src/components/Input/Location.js

We should only report errors which are not already handled by our Autocomplete implementation.

Don't send autocomplete errors for no-results

---

package.json
public/index.html
src/components/Input/Location.js

Bringing over https://github.com/18F/samhsa-prototype/pull/1
> Pinning our google maps javascript API version to quarterly(3.38)
> 
> Also tackling CBHSQ#557 here by:
> 
> Preventing 3rd party requests while pre-rendering the site. This means DAP, google analytics, and google maps are not loaded during pre-rendering.
> Setting a value for googleCallbackName on the PlacesAutoComplete component. The presence of a value allows the App to load without google maps being present.
> Preview branch: https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/pin-gmaps/

Sync w/ 18F/samhsa-prototype
