CBHSQ/findtreatment

src/components/Home.js

Added @amandacostello's drafted content for the 4 boxes below the treatment locator.

Update stage subtitles in getting started

---

src/utils/filters.js

Updating existing filter options within the drop downs to reflect https://docs.google.com/document/d/1dQuoLrDbZADz18vt0UJDQhx1BUI6NEXoJMWniRJS86o/edit#heading=h.agtqznhplhoz
We will need to move some to the advanced section but I will create a separate issue for that once confirmed.

Updating filter options

---

src/components/App.js
src/components/Banner.js
src/components/Form/SearchFilter.js
src/components/Form/SearchHome.js
src/components/Input/Label.js
src/components/Input/Location.js
src/components/Input/Select.js
src/components/Nav.js
src/components/Pagination.js
src/components/Results.js
src/css/tailwind.src.css
src/utils/api.js
src/utils/filters.js

Using `styled-components` to remove some of the styling from the jsx.

Clean up styles

---

src/components/Input/Location.js

Adds support for places autocomplete for US territories

---

package.json
src/actions/filters.js
src/actions/filters.test.js
src/components/Form/SearchFilter.js
src/components/Form/SearchFilter.test.js
src/index.js
src/plugins/search.js
src/reducers/index.js
src/store.js

Fixes #13 
* Only clears language for now
* Adds filter actions, advanced filter plugin to redux-form reducer, and
dispatch method to search component
* Updates package.json with `dev` script that docker-compose file expects

Clear advanced filters on visibility toggle

---

src/utils/api.js
src/utils/filters.js

Fixes https://github.com/18F/samhsa-prototype/issues/18
Preview: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/samhsa-prototype/bh-distance-all/

Add option to see all results

---

src/utils/filters.js

Updating filter names based on @amandacostello's content doc: https://docs.google.com/document/d/1gnoON2VLdI5HBVG1dcghdfedzwuj1KJed62b1-71Oz8/edit#

Update filter names

---

src/components/Card.js
src/components/Details.js
src/components/Form/Button.js
src/components/Form/Filters.js
src/components/Form/Homepage.js
src/components/Home.js
src/components/Input/Location.js

Fixes #29 
* Disables search button on homepage when an invalid location is present
* Adds <Button> styled component
* Automatically select the first valid suggestion when a user blurs the
location input field.
* Adds <Homepage> component-level submit handler to check for valid location
prop — this is done so that we can avoid using the native `disabled` property
on the submit button. Using that property breaks tab order and may negatively
impact users who rely on assistive devices

Prevent searches with invalid location data

---

src/utils/filters.js

We are going to add one MH-specific filter option to type of care to get a sense of the MH engagement. 
(NOTE: I am not sure if I can just add this so going to create a branch to check before merging)

Adding new filter option under type of care

---

src/actions/filters.js
src/components/Form/Filters.js
src/components/Form/Filters.test.js
src/components/Input/Location.js
src/components/Results.js
src/plugins/filters.js

Add button to reset filters on ResultsList page

---

src/components/App.js
src/components/Card.js
src/components/Details.js
src/components/Footer.js
src/components/HelpLine.js
src/components/Nav.js
src/components/NoMatch.js
src/css/tailwind.src.css

Fixes https://github.com/18F/samhsa-prototype/issues/12
Fixes https://github.com/18F/samhsa-prototype/issues/42
Adds a 404 page for any nonexistent routes. Federalist is only able to point to a path on the master branch for this page, so it must be merged to master in order to preview.
Also sets a default link color, and fixes an issue with the mobile menu.

Add 404 page

---

src/utils/api.js
src/utils/api.test.js

Tests the various conditions with the `buildParams` reducer.

Adds tests to API query reducer

---

src/components/Home.js
src/components/Nav.js

Changed to "Quickly find providers who treat substance use disorders and addiction"

Update homepage and nav labels

---

src/components/Form/Homepage.js

Adds default distance to homepage search so that it does not return all results.

Add default distance to homepage form

---

src/components/Form/Filters.js
src/components/Form/Homepage.js
src/components/Home.js
src/components/ResultsList.js

Fixes https://github.com/18F/samhsa-prototype/issues/53

Add integrated content

---

src/components/Banner.js
src/components/Header.js
src/components/HelpLine.js
src/css/tailwind.src.css

Fixes https://github.com/18F/samhsa-prototype/issues/59

Adds beta banner

---

src/components/Home.js
src/utils/topics.js

- Converted recovery section to "paying for treatment"
- Updated slug for this section

Updating info content boxes

---

src/components/Home.js

- Updated treatment options and understanding addiction ledes

Updated text inside content boxes on home page

---

public/index.html
src/components/Input/Location.js
src/components/MapContainer.js
src/components/MapContainer.test.js
src/utils/constants.js

Pull out API key into separate constants file.

Move Google API key to constants

---

src/components/Details.js
src/components/Map/DOMInfoWindow.js
src/components/Map/InfoWindowEx.js
src/components/Map/InfoWindowText.js
src/components/Map/MapContainer.js
src/components/Map/MapContainer.test.js
src/components/Results.js

Fixes https://github.com/18F/samhsa-prototype/issues/26

Add additional details to map infowindow

---

src/components/Card.js
src/components/Details.js

Fixes https://github.com/18F/samhsa-prototype/issues/28
Adds driving directions link to detail view.

Add link for driving directions

---

src/components/NoMatch.js
src/components/NoResults.js

Fixes https://github.com/18F/samhsa-prototype/issues/55
Revises content on error/404 page.

Update error message

---

src/components/Card.js
src/components/Details.js

Derive the details page from passing in the `frid` and pulling the associated details from the store.

Refactor details component to pull from redux store

---

src/components/HelpLine.js

- Updated helpline text
- Created a line break for responsive view

Updated helpline text

---

package-lock.json
package.json
src/actions/filters.js
src/components/Form/Homepage.js
src/components/Form/Homepage.test.js
src/plugins/filters.js

Fixes bug with location field displaying old data.
To recreate: Search for a location on homepage. Get results. Hit back to go to homepage. Search for a new location, see that results are displayed accurately, however the old location is still present in filter box.

Reset filter location on subsequent homepage searches

---

src/components/Card.js
src/components/Details.js
src/components/Footer.js
src/components/Form/Filters.js
src/components/Map/InfoWindowText.js
src/components/Nav.js
src/components/NoMatch.js
src/components/NoResults.js

- Updated "schedule appointment" language to "call"
- Removed "print provider" button
- Shifted from using the word "our" to "SAMHSA" on mission in footer, no results, and error messaging
- Removed links in footer (update your information, social media)
- Changed “Locate treatment” wording on top nav to “search for treatment”
- Updated URLs in footer (FOIA, USA.gov, list your facility, accessibility, submit feedback)

Made additional changes from our audit task list

---

src/components/Details.js
src/components/Form/Button.js

Fixes https://github.com/18F/samhsa-prototype/issues/88
Preview:

Fix alignment of buttons on details page

---

package-lock.json
package.json
src/components/Form/Filters.js
src/components/Form/Filters.test.js
src/components/Results.js

Fixes: https://github.com/18F/samhsa-prototype/issues/50
Initial pass at mobile layout for results page.

Results page mobile view

---

src/components/App.js
src/components/Page.js
src/components/ScrollToTop.js

Fixes https://github.com/18F/samhsa-prototype/issues/91
Creates a sticky side nav and smoothly scrolls to section of page when clicked.

Adds sticky side navigation and smooth scrolling

---

src/components/Form/Filters.js

- Removed gender filter (because of weird filtering logic and facilities that didn't answer genders accepted are not showing up)
- Moved age filter to advanced filters
- Removed flex sizing on age filter

Updated filters

---

src/components/Page.js
src/utils/topics.js

Fixes https://github.com/18F/samhsa-prototype/issues/92
- Increases spacing and adds dividers between topics
- Limits line length for better readability
- Adjust size and margin of headings, paragraphs, and lists

Iterate typography on info pages

---

src/components/App.js
src/components/Form/Filters.js
src/components/Form/Filters.test.js

Move to filter component where it is needed.

Defer languages endpoint request

---

package-lock.json
package.json

Removing a few unused packages and relocating some local dev packages.

Clean up npm dependencies

---

src/components/Details.js
src/components/Form/Filters.js
src/components/Input/Select.js
src/components/Page.js
src/components/ResultsList.js

Fixes https://github.com/18F/samhsa-prototype/issues/99
Preview: https://cg-efcd7c90-b365-4336-8b87-6174f1975c99.app.cloud.gov/preview/18f/samhsa-prototype/bh-info-linked/

Add links to content

---

src/components/Home.js
src/utils/filters.js

- Added two new filters - mental health services and co-occurring (which will later have different functionality, pending SAMHSA approval)
- Updated language on homepage to remove section about licensing

Made changes to add mental health filters

---

src/components/Pagination.js

Fixes https://github.com/18F/samhsa-prototype/issues/86
Adds proper disabled, active, hover states to pagination component.

Finish styling pagination component

---

src/components/Nav.js

Fixes https://github.com/18F/samhsa-prototype/issues/80

Add hover and active state to top nav

---

src/components/NoResults.js

- Updated 'no results' messaging to include expanding radius

Resolves: #136

---

src/components/App.js
src/components/Form/FormFilters.js
src/components/Results.js
src/components/ScreenContext.js

Allows access to current screen size from all components.

Add screen size context

---

CONTRIBUTING.md
LICENSE.md

Documentation updates, no site impact.

Initial version of contributing and license docs

---

src/components/Header/HeaderHelpLine.js
src/components/Loading.js
src/components/NoMatch.js
src/components/NoResults.js
src/utils/constants.js

Small tweak to make sure helpline phone number is consistently presented.

Add helpline number to constants

---

src/components/Details.js
src/components/Input/Button.js

Fixes https://github.com/18F/samhsa-prototype/issues/25
Preview:

Add return to results link on details page

---

src/components/App.js
src/components/Home.js
src/utils/content.js

Pulls heading and blurb for the homepage cards from the existing content.js file since it the content is already in there, eliminating the need to duplicate it in the Home component
Other small consistency/styling improvements.

Clean up homepage

---

src/utils/constants.js

Fixes https://github.com/18F/samhsa-prototype/issues/158
Previously 10 miles, now 25 miles from center point of location.

Change default search radius (25mi)

---

src/utils/content.js

Fixed spacing issues around <strong> and <a> tags where words were running together.

Updated spacing

---

src/utils/content.js

Added a few more spaces in the info content due to weird {' '} that's required sometimes

Updated more spaces

---

src/components/Form/FormFilters.js
src/utils/constants.js
src/utils/filters.js

Fixes https://github.com/18F/samhsa-prototype/issues/163

Fix for distance dropdown

---

src/components/Card.js
src/components/Card.test.js
src/components/Details.js
src/reducers/facilities.js
src/utils/misc.js

This converts the services data returned with each facility from an array like:
```
services:[
{f1: "Type of Care", f2: "TC", f3: "Substance use treatment"},
{f1: "Service Settings (e.g., Outpatient, Residential, Inpatient etc.)", f2: "SET", f3: "Outpatient; Intensive outpatient treatment"},
{f1: "Type of Opioid Treatment", f2: "OT", f3: "Do not use medication for opioid addiction"}
...
```
into an object accessible by service code:
```
{
AGE: {name: "Age Groups Accepted", values: ["Adults", "Young adults"]},
AS: {name: "Ancillary Services", values: ["Case management", "Consumer-run (peer-support) services", "Self-help groups", "Social skills development"]},
ASSES: {name: "Assessment/Pre-treatment", values: ["Comprehensive substance use assessment", "Outreach to persons in the …
```

Add function to convert services array into object

---

package.json

Helps compile javascript specifically for IE 11.

Add IE 11 to browsers list

---

src/components/Input/Select.js

Hide dropdown arrow on select box IE 11

---

README.md

For #182, adding additional content to the `README.md`. 
Highlights include details and limitations of local develop, guidance for collaborators, and referring feedback/commends to the existing google form in place for findtreatmentbeta.18f.gov.

Update readme to reflect current state

---

src/utils/content.js

Linked to SAMHSA's state agency url in info content

---

.eslintrc.json
package-lock.json
package.json
src/components/Form/FormFilters.js

Extends linting abilities of eslint to catch a11y issues.

Add eslint-plugin-jsx-a11y

---

src/components/App.js
src/components/Footer.js
src/components/Header/HeaderNav.js
src/components/Header/index.js

Addresses:
https://dequeuniversity.com/rules/axe/3.3/region?application=axeAPI
https://dequeuniversity.com/rules/axe/3.3/landmark-one-main?application=axeAPI

Add html and aria landmarks

---

package-lock.json
package.json
src/components/App.js
src/components/Content.js
src/components/Content.test.js
src/components/Details.js
src/components/Error.js
src/components/NoMatch.js
src/components/Results.js
src/utils/constants.js

Fixes https://github.com/18F/samhsa-prototype/issues/185
Adds unique page titles to various routes.

Add dynamic page titles

---

src/components/Input/Location.js
src/components/Input/Select.js

Added missing `id`s to properly connect labels to their respective inputs.

Connect labels to inputs

---

src/components/Map/MapContainer.js

Fixes https://github.com/18F/samhsa-prototype/issues/216

Properly zoom google map when there is only one result

---

src/actions/facilities.js
src/actions/facilities.test.js
src/actions/facility.js
src/actions/facility.test.js
src/plugins/filters.test.js
src/reducers/facilities.test.js
src/reducers/facility.test.js
src/reducers/languages.test.js

Add tests to various reducer methods

Add tests to reducers

---

src/utils/content.js

Since this isn't really a list of types of providers, like the types of treatment section is, I wanted to update the name of the section to reflect more of what it actually is.

Update language for Types of Providers

---

src/components/Form/FormFilters.js

Fixes #238 
Per @hursey013, we will also need to make changes to the label on the card and details pages (and maybe elsewhere) but I will leave it to him to do that as part of this PR or otherwise (if otherwise, let me know and I can create a separate issue)

Update 'type of care' filter label to 'type of treatment'

---

src/components/Form/FormFilters.js
src/components/Input/Location.js

Small fix to bring styles of location dropdown component in line with other style conventions.

Consolidate location picker styles

---

src/components/Card.js
src/components/Map/InfoWindowText.js
src/utils/api.js
src/utils/misc.js
src/utils/misc.test.js

Adds basic tests to a handful of utility functions.

Add tests to misc utility functions

---

src/components/Card.js
src/components/Details.js
src/components/Error.js
src/components/NoMatch.js

This uses consistent styles for buttons, preventing the scenario where a button is nested inside a link, causing multiple focus states on the same element.

Fix multiple focus on buttons

---

src/utils/filters.js

Updated inline text for filters

---

src/components/Card.js
src/components/Card.test.js

For #284, render 0 miles results and do not pluralize 1 mile.

Handle distance edge cases

---

src/utils/content.js

- Updated understanding addiction content (consolidated two sections)
- Added transitional housing content

Updated content

---

src/components/App.js
src/components/Content.js
src/components/Content.test.js
src/components/Header/HeaderNav.js
src/components/Input/Location.js
src/utils/content.js

Initial changes to address https://github.com/18F/samhsa-prototype/issues/223
Moves away from anchor links and gives each subsection of content its own route/page.

Separate route for each info page

---

src/utils/content.js

Reorder subsections within Treatment Options content

---

src/components/Results/NoLocation.js
src/components/Results/NoResults.js

Resolves #335 
Updated both "No Results" and "No Location" empty state styles.

Updated "No Location" and "No Results" empty state styles

---

src/components/Card.js
src/components/Details/DetailsLocation.js
src/components/Map/MapStatic.js
src/components/Map/MapStatic.test.js
src/utils/constants.js
src/utils/misc.js
src/utils/misc.test.js

Resolves #347 
Updates the address styles and links per the issue. Some refactoring to consolidate the address formatting and generation of external google maps link.

Update address styles

---

package-lock.json
package.json
src/components/Footer.js

Resolves #254 
Here is an initial take of adding the link. Added @amandacostello as a review for feedback on the actual content.

Ådd GitHub link to footer

---

src/components/Details/DetailsLocation.js
src/components/Details/DetailsPayment.js
src/components/Map/MapStatic.js
src/utils/misc.js
src/utils/misc.test.js

**Before:**
**After:**
Also moved the formatting of the distance to a helper function.

Add horizontal rules and location distance to details page

---

src/components/Error.js
src/components/Error.test.js
src/components/NoMatch.js

Focus on the `h1` when an error occurs

---

public/index.html

Fixes https://github.com/18F/samhsa-prototype/issues/327
Preview:

Adds a message for folks accessing the site without javascript

---

src/components/Input/Button.js

Decrease disabled state opacity from 75% to 50%

---

src/components/App.js
src/components/Content.js
src/components/Home.js
src/components/Results/index.js
src/components/ReturnToTop.js
src/components/ScrollToTop.js
src/utils/constants.js

Add `return to top` link

---

src/components/Details/DetailsLocation.js
src/components/Details/index.js
src/components/Input/Button.js

Additional design improvements with a focus on responsive design.
Before:
After:

Details page visual design improvements

---

src/components/Input/Label.js

Fixes https://github.com/18F/samhsa-prototype/issues/392
Preview:

IE11 input alignment fix

---

src/components/Details/DetailsLocation.js
src/components/Details/DetailsPayment.js

Fixes https://github.com/18F/samhsa-prototype/issues/391
Preview:

IE11 details page content overflow fix

---

src/components/ReturnToTop.js

Resolves https://github.com/18F/samhsa-prototype/issues/412

Keep route the same when using return to top link

---

src/components/Content.test.js
src/components/Header/HeaderNav.js
src/utils/content.js

Resolves #419 
- Changed order of content sections on top nav
- Changed order of content in info content section
- Will leave home page bottom of the fold content section as is

Reorder top nav and content section

---

src/components/Details/index.js

Resolves https://github.com/18F/samhsa-prototype/issues/431

Add meta description to details

---

public/robots.txt

Reverts 18F/samhsa-prototype#440

Revert "Temporarily remove robots.txt"

---

src/utils/content.js

A lot of content has moved around, but no pages have been renamed. I would like the "It's hard to stop on your own" page to be deleted; its content made more sense on another page, so that page is empty now.

Content updates

---

src/utils/content.js

Fixes #447 
@davemcorwin - I followed Brian's directions here but would appreciate your approval to verify if I did it correctly. Let me know if you have any questions! Thanks

Used link component on content.js and update internal content links

---

package-lock.json
package.json

Updating javascript dependencies

Update js dependencies

---

src/components/Input/Location.js

Resolves #455
Using this branch and PR to test higher debounce timing for our location autocomplete.

Fine tune autocomplete

---

src/components/Content.js
src/components/Content.test.js
src/components/Details/index.js
src/components/Details/index.test.js
src/components/Input/Button.js
src/components/Input/Radio.js
src/components/Loading.js
src/components/Results/index.js
src/components/Results/index.test.js
src/index.js

Eliminates the console errors in development and isolates/standardizes usage of tailwind theme in styled components.

Refactor use of styled components theme

---

src/components/BackToSearchResultsLink.js
src/components/Content.js
src/components/Content.test.js
src/components/Details/index.js
src/components/Details/index.test.js

Resolves #484 and #481 
Note: this was previously like hitting the "back" button, it is now an actual link...

Add Back to search results link to content, refactor to component

---

src/components/Details/DetailsLocation.js

Open Get Directions link in new tab

---

src/components/Results/index.js

Scroll to header when criteria change so users can see loading animation

---

src/utils/content.js

- Pulled the outbound link file into the content util
- Updated link tags to outbound link tags

Update links in content section to outbound links

---

src/utils/content.js

Add published date for content

---

src/components/Error.js

Resolves #508.
Updated error messaging for peak traffic. I'll create an issue to reverse this after launch week.

Update error message for launch

---

src/components/NoMatch.js

Set og:url equal to root url for 404 pages

---

src/components/Card.js
src/components/Map/MapStatic.js

Resolves #509 
Slight redesign to remove the static maps. The goal was for this to be a very simple comment and replace, but the changes are a bit more invasive than that. If we create an issue to reinstate the the static maps, let's make sure to link to this commit/PR as a reference.

Temp fix to remove static maps

---

src/components/App.js
src/components/NoMatch.js
src/index.js

This is replaced on application boot up by the correct page.  Movies and details pending

Use a loading spinner for the pre-rendered 404 page

---

.env.production
src/actions/facilities.js
src/components/Input/Location.js
src/middleware/analytics.js
src/utils/api.js

Target new GA and rework event categories

---

README.md
docs/architecture.md
docs/deploying.md
docs/developing.md
docs/testing.md

Taking a pass through our existing documentation in github to more fully describe the technical landscape of this project including but not limited to:
Architecture of the app
Deployment of the site (both via Federalist and a manual alternative)
Testing the app
Developing with the code base

Updating docs to add structure and detail

---

src/components/Home.js

Add a hidden link to statically render error page.

Statically render error page

---

src/components/Footer.js

- Changed "list your provider" link to one that talks about the process rather than the direct form

Update BHSIS link in footer

---

src/components/Error.js

Resolves https://github.com/CBHSQ/findtreatment/issues/512

Update error message post-launch

---

package.json

Use chrome within federalist build container for react-snap

Update package.json to set options for react-snap

---

README.md
src/components/Footer.js

Replaced old lifeline information with new 988 Lifeline

Update 988 Lifeline information in Footer.js

---

src/components/Footer.js

Replaced old lifeline information

Updated 988 Lifeline information in Footer.js
